### ISSUE TITLE
Numbers in person corner

### ISSUE THREAD

**Issue by adamboche** [JeffreyBLewis/WebVoteView#115]
There's a number in the bottom left corner, not sure what it is.

http://128.97.229.160/person/4248

![image](https://cloud.githubusercontent.com/assets/19828875/21943048/67fe4d7e-d984-11e6-98fb-d17bb628d609.png)

**Comment by aaronrudkin** [comment]
Intentional and used to debug something that's half-implemented--this page is generated in sort of a weird way (dumb decision I made earlier when re-writing the code we inherited from the Django version of the page) so I can't do my normal debugging in the JS console. Thanks. I will keep the issue open until I suppress this.
