### ISSUE TITLE
How to indicate selected legislator triangles?

### ISSUE THREAD

**Issue by adamboche** [JeffreyBLewis/WebVoteView#125]
Currently, when you select legislator in a box, they slowly grows into larger triangles. This is fine, but I find it a bit unintuitive. The slowness of the growth seems at odds with the expected immediate feedback of selecting something. 

I think we want it to be immediately highlighted in some way. This could be fast-growth, if it isn't a performance issue, or perhaps we could replace selected triangles with dark-bordered triangles?

**Comment by JeffreyBLewis** [comment]
Not sure how much control we have over this without hacking hard on DC.js.

**Comment by aaronrudkin** [comment]
Yes, this is very odd; most of DC's chart types add a .selected class to the selected items, but the scatterplot does not. I agree with Jeff that there is not an obvious way to do this. I can probably hack around it, but I have eliminated the quickest fix. :(

**Comment by aaronrudkin** [comment]
Okay I think the way to do this is:
1) When a filter change occurs (maybe just on the nominateScatterPlot), intercept it (we do this already for the filter bar)
2) Iterate through the data, and intercept which items have been filtered.
3) Now iterate through the path items underneath the chart. For each data point, if the item has been selected, ensure it has the class "selected". If not, ensure it does not have this class. I have already set the style in the CSS so that this class will display an outer stroke.

It's not immediately clear to me how you do the data point -> path svg mapping. nominateScatterChart.chartBodyG().selectAll("path") will give you the SVG paths, nominateScatterChart.chartBodyG().selectAll("path").each(function(n, i) { }) will probably give you the data points, but I don't know how you connect the two. It's really weird. Anyway, I'll pick this up again when I get some more time.

**Comment by JeffreyBLewis** [comment]
I think that in v2.1 of dc, you will see that it deals with this (if I
understand the issue), by shrinking the points that are not selected.
This might be all that we need without adding the stroke.

>
>

**Comment by adamboche** [comment]
Nice. Should the box that appears when you click be a bit smaller? When
guys are densely packed, it's hard to get only the one you want with a
bigger box.
