### ISSUE TITLE
District map is not draggable

### ISSUE THREAD

**Issue by lukesonnet** [JeffreyBLewis/WebVoteView#135]
On the district page, I cannot drag the map around (or drop a pin).

Is this easy/doable?

**Comment by JeffreyBLewis** [comment]
Map now draggable and also has zoom control.   Leaving issue open in case @aaronrudkin had a reason for not implementing these features.

**Comment by aaronrudkin** [comment]
The only reason I had disabled it was to avoid people with touchpads (or worse, tablets) getting a bad experience when their scrolling accidentally caught focus inside the district map and zoomed themselves out like crazy.

I also didn't want people to assume that because they moved the map, we would re-run the search query for the new viewport (although this is possible--just not implemented yet).

**Comment by JeffreyBLewis** [comment]
I think the zoom now only works with +/- buttons but haven't actually tried with a gestures on a tablet.

**Comment by lukesonnet** [comment]
I'm going to consider this closed. This is a mobile/tablet problem if it exists.
