### ISSUE TITLE
Data page

### ISSUE THREAD

**Issue by aaronrudkin** [JeffreyBLewis/WebVoteView#14]
Everything on the data page should be classified based on whether or not we wish to continue producing it or not. Everything we plan to continue producing needs to be linked instead of broken.

**UNCLASSIFIED**
- DW-NOMINATE Program With Examples
- DW-NOMINATE Probabilities for Legislator Choices: 1st to 112th Congresses (huge file, not sure if we should maintain? People can get this through the main interface if they really want to)

**PRODUCE EVERY UPDATE**
- Percent Voting on the Winning Side by Member -- Houses/Senates 1 - 112 (**memberCSV**)
- Party Unity Scores by Democrat and Republican Members: 1857 - 2012 (**memberCSV**)
- Common Space DW-NOMINATE Scores 1st to 112th Congresses (**memberCSV**, **rollcallCSV**)
- Cutting Line Angle Files for the House and Senate 1st to 112th Congresses (**rollcallCSV**)
- Party and Chamber Medians, 1 - 112 Congresses (DW-NOMINATE Scores) (**partiesCSV**)
- Party Unity Scores by Congress: 1879 - 2012 (**partiesCSV**)
- Political Polarization Measures: 1879 - 2012 (either as a polarization Rmd or a congress-chamber level csv?)
- ORD file for present congress

**PRODUCE EVERY SESSION OF CONGRESS**
- DW-NOMINATE Scores 1st to 112th Congresses (fixed after the end of the last congress, only updated every two years)
- One-Congress-at-a-Time DW-NOMINATE (Nokken-Poole) data for the House and Senate 1st to 112th Congresses
- ORD files for past congresses

**MAINTAIN ONLY AS LEGACY KEITH FILES**
- Rank Orderings all Houses and Senates -- 1st to 112th Congresses
- Clausen, Peltzman, and Issue codes for 1st to 113th Congresses 

Static text files that will never change should be put in **/static/data/**. Legacy files should be put in **/static/data/legacy/**. Ongoing files should output to **/static/data/current/**. I will write a cronjob to automagically back up the current folders each week.

The template itself is **/var/www/voteview/views/data.tpl**. Feel free to edit it and commit changes.

Please use comments to either suggest placement for these files, place them, or note when you've created a script to output them.

**Comment by lukesonnet** [comment]
This will be handled after the schema change (Issue #22).

**Comment by lukesonnet** [comment]
I'm going to make my own todo list that I will edit here. I added names so I could tick them off on the list above.

I'm also going to edit your post to reflect our discussions about this page.

- [ ] rollcallCSV - CSV files for rollcalls (by congress-chamber), need cutting angles, otherwise done
- [ ] memberCSV - CSV files for members (by congress-chamber)
- [ ] icpsrCSV - CSV files for icpsr (by congress-chamber)
- [ ] partyCSV - CSV file for parties (one file where rows are party-chamber-congress and one file that is over whole db)
- [ ] ORD files for past a present congresses
- [ ] Polarization .Rmd

Then I will add legacy support that continues to output old .DAT files for legislators and rollcalls, but nothing else. We should encourage everyone to move to .csv
- [ ] rollcallDAT
- [ ] memberDat

**Comment by lukesonnet** [comment]
This data page is set up. I will open a new issue with enhancements and ideas going forward, but the basic data is here and available.
