### ISSUE TITLE
Issues raised by Sarah Binder at GWU

### ISSUE THREAD

**Issue by JeffreyBLewis** [JeffreyBLewis/WebVoteView#165]
Hi Jeff

The new voteview site looks great. 

If you don't mind...I have a few questions. I tried to submit via the site, but I got the error message that the site can't accept messages from "disposable email address services."  (I tried to send from gwu.edu)

Anyway, can I bother you and your UCLA voteview folks with my questions?  Pasted questions below.

Thanks!

Sarah

**Comment by JeffreyBLewis** [comment]
HERE IS MY QUICK RESPONSE TO HER INCLUDED HERE FOR REFERENCE:

Sorry about the problems.  I will try to get those addressed ASAP.   I think I can answer the most important one right off which relates to the vote descriptions.  From the download page you can get nominate estimates for the votes which include (I think) all of the info that was in previous description file plus some other things.  Here is an example link.  

https://voteview.polisci.ucla.edu/static/data/csv/rollcall/rollcall_house_115.csv

Let me know what you think of that as a substitute.   I think the ORD have the same format.  I pulled them into WNOMINATE in R and they seemed to work correctly.  Let me know if you find an discrepancies with your code, I think all of that metadata should be where you expect it to be.

Best,

Jeff

**Comment by aaronrudkin** [comment]
Hi Jeff,

The questions didn't seem to get pasted in the version of the issue here. All I get is the issue about the contact page. I will check in to why gwu.edu is being blacklisted (the intent of that is to blacklist stuff like mailinator.com and other fraudulent signup services so as to avert spam).

**Comment by aaronrudkin** [comment]
Fixed the issue with the contact form -- wasn't a GWU specific issue, was an issue with the blacklist having a blank link and thus matching every email. It didn't last I tested. It's moot anyway because the email was going to contact@voteview.polisci.ucla.edu which I don't think is an actual email yet.

I fixed it, updated the contact email to <jeff's email>@<our university>.edu, and did a test confirming that a Sarah wouldn't get this issue anymore.

Please thank Sarah for being diligent enough to not only report an issue, but also report that our report an issue function wasn't working.

**Comment by lukesonnet** [comment]
Hi Jeff, as Aaron said we can't see the questions.

However, one of the priorities for the data page will be documentation which should help with these kinds of questions.

**Comment by JeffreyBLewis** [comment]
**Here is the missing part of SB's original message:**

Here's what I tried to submit:

> Hi all,
>
>The new site is great.  I'm a big fan.  But I have a few questions:
>

> 1. What happened to the old roll call vote dictionaries (codebooks) that Jeff used to post on his data site for the recent Congresses?  Example: : S114desc.csv Those Excel files were very helpful for making sense of the roll call data (and making sure that I uploaded the .ord files correctly into Stata.
> 
> 2. When I try to use the download function to collect the roll call votes (via the search function), I get an error message everytime. It says "You can only save stashes of 250 votes or less" regardless of the number of votes I try to download.
> 
> 3. Just to confirm -- the .ORD vote files are organized the same as the old ones on Jeff's site and voteview? Just want to make sure I have the variables (v1-v10) correct before importing to Stata. 
> 
> Thanks very much. 
> 

I replied RE nos 1 and 3 (which relate also to the ticket from @aaronrudkin  on documenting the data page better.    No. 2 seems like a bigger issue.

**Comment by lukesonnet** [comment]
I can work on problem 2 tomorrow.

**Comment by lukesonnet** [comment]
I can't seem to replicate problem 2. Anyone else?

**Comment by aaronrudkin** [comment]
I couldn't replicate it either.
