### ISSUE TITLE
Washington DC addresses on district page have some errors

### ISSUE THREAD

**Issue by lukesonnet** [JeffreyBLewis/WebVoteView#176]
https://voteview.polisci.ucla.edu/district/77%20H%20St%20NW%20washdc%2020001

It is showing the current maryland senators (I don't think it should as that is not currently the case) and it shows people as late as 1993, is that correct?

**Comment by aaronrudkin** [comment]
The current senators are inaccurate and I will fix this. It uses the last state it found a valid rep in to do the lookup for the senators.

The people in the 98th through 102nd I think is probably an error in the district shapefile for those. I confirmed from Jeff's online copy of the data that it shouldn't be right: [H and North Capitol is clearly inside the district, not Maryland.](https://github.com/JeffreyBLewis/congressional-district-boundaries/blob/master/Maryland_98_to_102.geojson) The map pin would suggest that the geocode worked properly, which means the question is why that lat/long pair is flagging as part of the Maryland 1st during that year. I'll verify that the lat/long pair is mapping to the district directly at the API level, and then in the DB level, and if it's still happening at the DB level I'll check if the problem is the raw data or Mongo's spatial queries.

**Comment by aaronrudkin** [comment]
Found the reason for the 98th to 102nd. 

Long version: Jeff's geo data includes the DC At-Large rep as a district--very specifically in the 98th to 102nd. My code doesn't prevent this from getting added. So our code is looking for a matching rep during those congresses.

The at-large handling code is weird, because we have at-large coded as 98 or 99 or 1 depending on the circumstance, while Jeff has it coded as 0 all the time. As a result, when I see a zero, I have to map to 1 or 98 or 99. Because of how this mapping works, I process it after the regular districts. I need to go back and grab the state name, which has been discarded from earlier when I processed the regular districts, so it uses a sort of "global state name" variable, which is set by the first state name it sees for the address. Because DC was Maryland in Congress 1, it thus looks for a Maryland at-large rep, including a Maryland rep for District 1.

Fixes:
- 1) Do not admit DC districts to the candidate lookup pool -> done now.
- 2) Keep better track of the state at the time of the at-large lookup to ensure in state-switching cases like MA/MD or VA/WV or DC that we don't have the wrong state for the wrong period. -> will do tomorrow.
