### ISSUE TITLE
Parties at a glance median tooltip

### ISSUE THREAD

**Issue by lukesonnet** [JeffreyBLewis/WebVoteView#178]
When the median is swinging pretty wildly from left to right on the parties at a glance plot when control switches hands it is really hard to get the median line tooltip. I assume this is because when the line is moving rapidly vertical its because it is in between congresses and there is actually no data there.

I honestly don't know how the DC for these tooltips work and if this is solvable.

**Comment by aaronrudkin** [comment]
It's not because of a lack of data (I could just round to the nearest or whatever), it's that the tooltip is pegged to the SVG point at congress n (which is invisible), not the line interpolation between congresses n-1 and n. If you look at the raw SVG you can see that both layers are present. 

I think the last time I checked it effectively was not possible to anchor a tooltip to the line itself, but maybe our DC upgrades have made this more viable.

**Comment by lukesonnet** [comment]
That's what I meant by no data, it's in the interpolation that is very vertical that the tooltip does not apear.

**Comment by aaronrudkin** [comment]
Okay, I managed to attach the tooltip to the SVG line. It's not perfect, and the vertical sections are still a little touchy, but they're less touchy than before. I also thicken the median line a bit to give you a bit more mouse target. Again, not perfect. (If you don't see the thicker line, refresh cache).
