### ISSUE TITLE
MAJOR PROBLEM WITH DATES IN THE DB!!!

### ISSUE THREAD

**Issue by JeffreyBLewis** [JeffreyBLewis/WebVoteView#200]
I received the following from Scott Moser and it looks very much like is correct:

> Dear Jeff,
> 
> Sorry for the (additional) bother, but I think there are a few errors with the dates in the 112th house data dictionary (rollcall_house_112.csv).  I've matched the vote view votes for the 112th house to govtrack, which gives different dates for a few votes:
> 
> 
> vv.id	date	link_govtrack	govtrack.date
> RH1120433	28/05/2011	http://www.govtrack.us/congress/votes/112-2011/h435	Jun 15, 2011
> RH1120660	28/05/2011	http://www.govtrack.us/congress/votes/112-2011/h663	Jul 28, 2011
> RH1120668	28/07/2011	http://www.govtrack.us/congress/votes/112-2011/h671	Jul 29, 2011
> RH1120676	29/07/2011	http://www.govtrack.us/congress/votes/112-2011/h679	Jul 30, 2011
> RH1120756	05/10/2011	http://www.govtrack.us/congress/votes/112-2011/h760	Oct 6, 2011
> RH1120868	30/11/2011	https://www.govtrack.us/congress/votes/112-2011/h872	Dec 1, 2011
> RH1121335	20/06/2012	http://www.govtrack.us/congress/votes/112-2012/h392	Jun 21, 2012
> 
> 
> Sorry if im' being dense.  Thanks again for all your help, and for providing this super-valuable resource!
> 
> Best,
> Scott

For example on dev:

% db.voteview_rollcalls.find({id:"RH1120433"},{date:1,clerk_url:1,vote_counts:1})

yields:

{ "_id" : ObjectId("580940afccba0283cfbea359"), "date" : "2011-05-28", "clerk_url" : "http://clerk.house.gov/cgi-bin/vote.asp?year=2011&rollnumber=435", "vote_counts" : { "9" : 10, "1" : 120, "6" : 303 } }

But if you go to the clerk's page at that url, the date says "15-Jun-2011" !!!  The rest of the info appears correct at least at first glance.  Not sure how this could be happening, but it needs immediate attention.

**Comment by adamboche** [comment]
Great catch by Scott and Jeff! 

Last month I uploaded the latest version of the K7MOA issue codes files to ensure consistency with the DTLs. At that time, Keith wrote to me:

> Again, this is the “Gold Standard”:
>  
> ftp://k7moa.com/junkord/H01_113_codes.TXT
>  
> and its Senate Counterpart:
>  
> ftp://k7moa.com/junkord/S01_113_codes.TXT

...
    
> You can get STATA files or Excel Spreadsheets as well as text.  These files are the definitive “clean” files as of the end of the 113th Congress and reflect all the corrections made up through mid-2015.

So I had uploaded the data in the codes file overwriting data from prior sources, expecting that differences between it and the records already present were corrections to the data. Indeed, Keith's work has made many real corrections to official records over the years; however, I'm not sure that this particular case is an example of that kind: it seems like the Clerk's report of the dates should be preferred to the codes file. I should've checked for this case, but I missed it -- my mistake there.

I have therefore overwritten the database to use the Clerk's data instead. Since Keith reports that the codes files are the gold standard incorporating years of corrections, I have written to him to check if this was in fact a correction made, which should be retained.

In particular, the [codes file reports](ftp://k7moa.com/junkord/H01_113_codes.TXT): 

> 112  433      362 0 15 25   5 28 2011  101  21  19 282   100  23  20 280  13 120   0   0   0   0 303   0   0  10  AGRICULTURE APPS -- INTL FOOD PROGRAMS

reflecting 2011-05-28, while the [Clerk reports](http://clerk.house.gov/evs/2011/roll435.xml) 2011-06-15 for that vote.

The dev database now reflects the Clerk's data:

> `{ "id" : "RH1120433", "date" : "2011-06-15" }`

and deployment to production is underway.

Please review this and let me know if anything doesn't seem right.

**Comment by adamboche** [comment]
@lukesonnet The flat files are corrected on dev, but not on production. Do you know how to get them all to move?

**Comment by lukesonnet** [comment]
The issue was likely the deploy script broke, before the rsync for the data happened, which might be why the website was down.
