### ISSUE TITLE
Crashing rendering pages for certain votes!

### ISSUE THREAD

**Issue by JeffreyBLewis** [JeffreyBLewis/WebVoteView#202]
I now get a 500 error of this vote:

https://voteview.polisci.ucla.edu/rollcall/RS0930167

and many others.  Yikes.

**Comment by lukesonnet** [comment]
This is still the wikipedia error, @aaronrudkin. You fixed this but I think something is not keeping that change sent to the production server.

**Comment by lukesonnet** [comment]
Okay, this error was because when 'wikipedia' was added to the orgMapping on views/search_result.tpl it wasn't added to orgMapping on views/vote.tpl. This probably shouldn't be split across both pages so I'll leave this open until that is resolved. Can't fix that right now but the main issue is resolved.

**Comment by aaronrudkin** [comment]
@lukesonnet Important to also add a check in views/vote.tpl to check if the label is there before rendering it (i.e. `if vote["key_flags"][0] in orgMappings` or similar).
