### ISSUE TITLE
Compress bio photos

### ISSUE THREAD

**Issue by fasouto** [JeffreyBLewis/WebVoteView#33]
I just checked the page and realize that the amount of images could be problematic (some pages have more than 200). It could be a good idea to optimize member images for the web.

I run `jpegoptim` and looks like we can save ~50% of the size using **lossless compression**. I have this in a branch, if you want I can create a PR.

**Comment by aaronrudkin** [comment]
Hi Fabio,

I was literally in the middle of checking for large member images as I saw your issue! In some cases I think the best solution will be replacing the image altogether, for example old members who have line drawing pictures rather than photos.

If you could leave your `jpegoptim` settings in a comment that would be ideal so we can be sure that newly added images pass through the same process. You can create a PR as well (please PR into dev branch instead of master) if you'd like to submit the pre-shrunk images.

**Comment by aaronrudkin** [comment]
One other thing -- if you want to submit a PR, please rebase to the current dev branch. A few photos have been replaced in the last day and we wouldn't want to revert them to merge in the compressed versions.

**Comment by fasouto** [comment]
Sure, I will add an PR with the script to compress the pictures with `jpegoptim` so if the images are updated it could be run again.
I'll do it once I got home.

**Comment by aaronrudkin** [comment]
We're doing some major changes to our database schema right now. I've merged your PR and after we do the db changes I'll do the image compression. Thanks!
