### ISSUE TITLE
Add endpoints in view instead of model

### ISSUE THREAD

**Issue by adamboche** [JeffreyBLewis/WebVoteView#37]
The slope/intercept are calculated directly from mid/spread. It seems redundant to keep them both in the db - i'm likely to forget to update them somewhere and we'll get inconsistency. Would it be ok to make this routine a view thing instead of including it in the data model?

    def add_endpoints(self):
        """Add attributes to nomimate attribute that aid in
        drawing cutting lines
        """
        self['nominate']['slope'] = None
        self['nominate']['intercept'] = None
        if (self['nominate']['spread'][0] == 0 and
                float(self['nominate']['spread'][1]) == 0 and
                float(self['nominate']['mid'][0]) == 0 and
                float(self['nominate']['mid'][1]) == 0):
            self['nominate']['x'] = [0, 0]
            self['nominate']['y'] = [0, 0]
        elif abs(float(self['nominate']['spread'][1])) < 1e-16:
            self['nominate']['x'] = [float(self['nominate']['mid'][0]),
                                     float(self['nominate']['mid'][0])]
            self['nominate']['y'] = [-10, 10]
            slope = 1000
            intercept = -slope * (float(self['nominate']['mid'][0])
                                  + float(self['nominate']['mid'][1]))
            self['nominate']['slope'] = slope
            self['nominate']['intercept'] = intercept
        else:
            slope = -float(self['nominate']['spread'][0] /
                           (float(self['nominate']['spread'][1]) *
                            self.dimweight * self.dimweight))
            intercept = (-slope * float(self['nominate']['mid'][0])
                         + float(self['nominate']['mid'][1]))
            self['nominate']['x'] = [10, -10]
            self['nominate']['y'] = [intercept + slope * xx for xx in
                                     self['nominate']['x']]
            self['nominate']['slope'] = slope
            self['nominate']['intercept'] = intercept

**Comment by aaronrudkin** [comment]
I agree 100% with the concept and it looks like the code is right. 

Two questions:
1) Would we prefer to keep slope/intercept and calculate mid/spread, or the reverse?

2) I think the title might be slightly mis-named. we're not talking about moving the code from model to view; we're talking about moving the code from static precalculation in the db into the model. Typically the view should not _do_ anything in MVC or similar architectures. We're pretty fast and loose about how we implement MVC but still.

I would imagine that this would be added into the searchVotes/downloadVotes API as something that's done while assembling votes?

**Comment by lukesonnet** [comment]
1) Mid-spread are what come straight out of Keith's DW-NOMINATE and pynominate as they are currently written. Of course, rewriting pynominate is no problem, and having the slope and intercept being computed when the numbers are being ingested into the DB upon updates or conditional estimation is also no problem. However, you can generate the slope and the intercept from the midpoint and the spread them but the reverse is not true. The DB should probably have the mid/spread instead of slope/intercept.

2) One problem with adding it to downloadVotes is if we intend to pull straight from mongo... then we have the same problem where we duplicate this kind of code. I don't know the issues with storing more information in the DB but I think this should remain as a static precalculation in to the DB. The mid/spread will be updated every time we run nominate, so we might as well just reingest it along with the mid/spread. Then this code only lives in one place.

Again, I don't know about the costs to large dbs in mongo.

**Comment by aaronrudkin** [comment]
There shouldn't be much penalty besides if we are querying by these fields (we don't) or indexing them (we don't). The main issue raised would be Adam's suggestion that the mid/spread and slope/intercept might be desynced due to people failing to sync them.

**Comment by adamboche** [comment]
Aaron - I agree about the terminology.

Having both in the db shouldn't be a problem in terms of performance. In
general, we want to avoid duplicating (1) code and (2) data. In the ideal,
whatever database schema we use should therefore avoid redundant data like
having only mid/spread, not also slope/intercept. Then to avoid duplicating
code, a function could be introduced into the api that generates the
slope/intercept as needed. Then any routine that wants slope/intercept
could go through that api procedure to get them.

**Comment by aaronrudkin** [comment]
This is done. The download votes API now deletes x, y, slope, and intercept from what it gets out of the database and then re-generates them using the above code (if spread/mid are present and valid). So everything on the dev server is using the above code, even on the old schema, and we'll be ready for the new schema.
