### ISSUE TITLE
Parties at a glance singleton dots

### ISSUE THREAD

**Issue by lukesonnet** [JeffreyBLewis/WebVoteView#63]
The singleton dots need to be cleaned up on the parties page.

**Comment by aaronrudkin** [comment]
I can turn these off easily, but is there a better option we want to investigate before I do?

**Comment by lukesonnet** [comment]
What was the issue again?

**Comment by aaronrudkin** [comment]
There's no issue. We have actual singleton major parties in the dataset at that period. We can't render them as a line; only as a scatter. If we turn them off, then we're saying those aren't major parties (even though they were the second biggest at that time, iirc.) -- if we leave them, we get a visual eyesore.

**Comment by lukesonnet** [comment]
Then the other line should break/not start at the singleton, no?

**Comment by aaronrudkin** [comment]
I'm not sure what you mean, but I'll go through the basic details so we can be sure to be on the same page:

- 33rd Congress: Major Parties: Democratic (Maj.), Whig (Min.)
- 34th Congress: Major Parties: Dem (Maj.), Opposition (Min.)
- 35th Congress: Major Parties: Dem / Rep. The opposition party disappears entirely.
- 36th Congress: Major Parties: Senate: Dem 25, Rep 22. House: Dem 130, Rep 92, Opposition 17.

Decision 1: Which parties do we show at each juncture? Right now, I just decide if someone is a major party and if they are, I show them. So even though the Opposition is a third party in the 36th Congress, I show them, because they were a major party in the 34th. Making matters more complicated, it seems that the two Opposition Parties may not be the same despite having the same ICPSR codes and being classed as the same by Keith. https://en.wikipedia.org/wiki/Opposition_Party_(United_States) <-- Northern = 34th, Southern = 36th. Do we want to split the Opposition Party into two? That sounds like a principled way to do it. If so, how do we allocate a new ICPSR ID to a party? After I split it, I would not visualize the 36th Congress Opposition Party on the plot. We'd only have one singleton, then.

Second, in terms of display. DC has to interpolate between elections to create the lines and there could be some weird behaviour there in the interpolation that is causing issues near edge cases. In addition, the way I override display for years where the party is not present (i.e. how I handle "NAs") is a little unusual. So there could be issues with the very end of the Whig line that make things look more disconnected than they should. Is there a display issue being caused by transforming something discrete into something continuous? I tried to look into whether a 1-congress party could be represented as a line--like by fuzzing the line to t-0.1 to t+0.1 or whatever--and no dice.

**Comment by lukesonnet** [comment]
Okay, I see. I see why you want a principled structure to what we display, but currently the dots are nonsensical and for people to understand them they would have to read your comment and go "oh esoteric historical coalitions and weird DC design flaws are why these dots are there." That said, I really don't know the solution here. @JeffreyBLewis?

**Comment by aaronrudkin** [comment]
I think we should:

1. Split the Opposition Party, giving Opposition Party (34th) the current ICPSR ID and creating a new ICPSR ID for Opposition Party (36th). Update all members.
2. No longer display Opposition Party (36th) in the parties at a glance map.
3. Consider what to do about the Opposition Party (34th) singleton in the party display; I could make it visually smaller, or I could potentially display the American (Know-Nothing) Party which is a non-singleton party present around that time.

Is this OK? Let's get this issue closed.
