### ISSUE TITLE
Stop words in searches

### ISSUE THREAD

**Issue by JeffreyBLewis** [JeffreyBLewis/WebVoteView#78]
Not sure how stop words are treated in out searches.  The search for "the and" (unquoted) returns nothing. The search "the" hangs (or at least is very slow) when I try it.  The stop words are marked up in the results which gives the impression that that stop words are used in the search.   I would say unless the query is quoted in the search the stop words shouldn't be used or marked up.

**Comment by aaronrudkin** [comment]
It seems like there are two things we want to do here:
1. Avoid highlighting stop-words in results unless it's an exact match or a quoted query
2. Give the user some feedback if their entire search is dropped due to being a stop word.

This is a list of Mongo's English stop words, which we can use to implement this on our side:
https://raw.githubusercontent.com/mongodb/mongo/master/src/mongo/db/fts/stop_words_english.txt

**Comment by aaronrudkin** [comment]
This is done. If the user searches only stop words, they will get a special error explaining their search words are too common. Highlighting is now a little more picky--it'll only highlight a stopword if there's an exact match.
