### ISSUE TITLE
Major problem with nominate calculations on some votes (RH1140043 for example)

### ISSUE THREAD

**Issue by JeffreyBLewis** [JeffreyBLewis/WebVoteView#87]
Have a look at

https://voteview.polisci.ucla.edu/rollcall/RH1140043

It appear to me that the yea/nay locations have be reversed!  And, lots of vote probabilities look like the they are based on reversed calculations as well...

Jeff

**Comment by lukesonnet** [comment]
Adam, this is likely keith's data since it probably wasn't conditionally
estimated (you should be able to check for a conditional flag in the mongo).

Luke Sonnet
PhD Student, Political Science
UCLA

On Nov 3, 2016 10:44 PM, "JeffreyBLewis" <notifications@github.com> wrote:

Have a look at

https://voteview.polisci.ucla.edu/rollcall/RH1140043

It appear to me that the yea/nay locations have be reversed! And, lots of
vote probabilities look like the they are based on reversed calculations as
well...

Jeff

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/JeffreyBLewis/WebVoteView/issues/87>, or mute the thread

**Comment by lukesonnet** [comment]
This is definitely broken: http://128.97.229.160/rollcall/RH1140002

Not sure what is going on here, but I will investigate. @JeffreyBLewis, have you been messing with the Y and N points?

**Comment by lukesonnet** [comment]
Is it possible that the code that adds endpoints is actually backwards? As in I think the spread and mid points might be reversed somewhere along the line?

@JeffreyBLewis, can you check lines 37-63, add_endpoints, in **model/downloadVotes.py** to see if the mid and the spread should be reversed? The answers it gives seem to be much more plausible when I plug in the data in reverse order.

**Comment by JeffreyBLewis** [comment]
Right. I am working on it.  

Jeff

**Comment by adamboche** [comment]
@JeffreyBLewis @lukesonnet Status?

**Comment by lukesonnet** [comment]
This seems fixed to me.
