### ISSUE TITLE
Download rollcall as PDF or print

### ISSUE THREAD

**Issue by adamboche** [JeffreyBLewis/WebVoteView#9]
I can imagine these rollcall pages being handouts in a class. Can we have a pdf or print button?

**Comment by aaronrudkin** [comment]
There are, I think, about three separate issues here:
1) Updating our stylesheet for print media (so that the header, footer, sidebar, etc. does not appear)
2) Making sure coloured images gracefully degrade into B&W
3) Actually implementing a print button (this is pretty trivial).

I think actual "generate a PDF" functions are more common with, say, academic articles that start as PDFs than with dynamic websites with lots of interactive components. IIRC statically rendering offline and outside a browser is relatively difficult because it would rely on terminal Javascript and SVG emulation, neither of which common browser emulators like mechanize do.

As a result, I don't think it makes sense to directly implement a PDF button. 

However, most browsers now have print-to-PDF capabilities. No idea if Windows 10 does natively, but you can use CutePDF or Foxit or other options to add a PDF print driver. OSX does natively at the system level. I would assume most Desktop linux distros do as well. Probably better to just make the print function look nice and then rely on users to select PDF as a print destination.

**Comment by lukesonnet** [comment]
Not sure if this is the right place, but the resolution on the PNG downloads of ideological space figures is pretty rough.

**Comment by aaronrudkin** [comment]
I will take a look at what it looks like right now. I am sure there are parameters to help improve the look

**Comment by lukesonnet** [comment]
I would like to add here that the **downloadXLS** feature and code is broken.

**Comment by aaronrudkin** [comment]
You can now print votes using your browser's print function, and it looks good. We don't degrade our colour maps to B&W--not sure if this is plausible--but the stylesheet is updated so some of the worst intrusions don't show up when printing, and I make a few other tweaks. Either way, a high school teacher can now print our stuff!
