### ISSUE TITLE
Search that "should" work but doesn't: Bush tax cut

### ISSUE THREAD

**Issue by JeffreyBLewis** [JeffreyBLewis/WebVoteView#90]
In a real use case, I tried to find all of the votes for the 2001 Bush tax cuts.   The bill was called the 
"Economic Growth and Tax Relief Reconciliation Act" and I could find some house votes using the name as the search text (though scoring seemed odd as the votes that matched the text exactly didn't appear first and searching for the quoted string returned no results (on dev).  The real problem is that there was at least on Senate vote (see https://www.govtrack.us/congress/votes/107-2001/s165), but none turn up in our search.

**Comment by JeffreyBLewis** [comment]
It looks like the info is in the db to make this happen:

> db.voteview_rollcalls.find({chamber:'Senate',congress:107,id:'RS1070165'},{document:1,id:1})
{ "_id" : ObjectId("580940adccba0283cfbe7e2f"), "id" : "RS1070165", "document" : { "document_short_title" : "Economic Growth and Tax Relief Reconciliation Act of 2001", "document_number" : "1836", "document_type" : "H.R.", "document_title" : "A bill to provide for reconciliation pursuant to section 104 of the concurrent resolution on the budget for fiscal year 2002.", "document_name" : "H.R. 1836" } }

but, it doesn't.

Best,

Jeff

**Comment by adamboche** [comment]
Indexed additional text fields. Looks like it's fixed.

**Comment by adamboche** [comment]
[image: Inline image 1]

**Comment by adamboche** [comment]
It finds it now searching not in quotes. It's RS1070165. However:
- It doesn't find it when you search the bill name in quotes.
- I would've expected RS1070165 to appear first, certainly before vote 69, which isn't the same thing.
@aaronrudkin any idea what's going on?

**Comment by lukesonnet** [comment]
I found the problem. When you search in quotes without a field name, it does the following:

- Prepend "description: " to the query
- Description is a "flexstr" which means it hits the full text index if there is no quotes, and it searches the field with an exact regex if there are quotes
- Because this query has quotes, then it will do a regex of just the "description" field.

We need to handle this better so it actually goes to "alltext" which searches all text fields. More importantly, we need to more appropriately handle the new fields Adam has added from the congressional record. I'm going to try out some solutions.

**Comment by lukesonnet** [comment]
Okay, so the issue is how a search handled a query without a field name explicitly denoted. Previously, it did the following:

- If " in query:
  - build candidate list of votes by passing the query to the full text index
  - within candidate list of votes, search **only the _description_ field**
- Else (no quotes):
  - pass query to full text index

Now instead it prepends "alltext: " instead of "description: ". Then it is handled the following way:

- If " in query:
  - build candidate list of votes by passing the query to the full text index
  - within candidate list of votes, search **all text fields** [_description_, _short\_description_, _vote\_desc_, _vote\_document\_text_, _bill_, _vote\_title_,  _vote\_question\_text_]
- Else (no quotes):
  - pass query to full text index

This is somewhat slower, but I haven't done speed tests. That said, I think it is the best way to pull together the major fields. Maybe we should cut out some of the text fields listed above, but for now this is probably the best solution. We might also want to build a facet for the question field so that people can subset to certain kinds of votes (with the caveat that this data only exists after some date).

**Comment by aaronrudkin** [comment]
I had planned to pull together the major text fields into a single text-indexed text field, but we hadn't yet achieved stability in what text fields would be there.

**Comment by adamboche** [comment]
Searching `"Economic Growth and Tax Relief Reconciliation Act"` (quoted) does not return RS1070165, but querying the db does. Is that I'm supposed to be doing quoted queries in the search box?

db.voteview_rollcalls.findOne({id: 'RS1070165', $text: {$search: "\"Economic Growth and Tax Relief Reconciliation Act\""}}, {cg_summary: 0, cg_subjects: 0, votes:0})
