### ISSUE TITLE
Adding tooltips and decorations to member lists on vote pages

### ISSUE THREAD

**Issue by adamboche** [JeffreyBLewis/WebVoteView#94]
_From @JeffreyBLewis on January 5, 2017 20:56_

We need to spice up the member lists on the vote pages and probably on the congress/senate pages in the following ways:

(1) When sorted by ideology, we should have a tooltip that shows the 1st dim nominate score on roll over.

(2) When sort by vote probability, we should have tooltip that shows the prob of a yea vote for each member.

(3) When sorted by ideology we should decorate the median member as well as the veto override pivot and the fillabuster pivots (senate only of course for that one).

_Copied from original issue: JeffreyBLewis/Rvoteview#12_

**Comment by adamboche** [comment]
_From @aaronrudkin on January 6, 2017 0:22_

I think this was probably intended for WebVoteView? But this all seems good.

**Comment by aaronrudkin** [comment]
I think I can implement 1 and 2 fairly reliably, and I will do 3 immediately.

**Comment by aaronrudkin** [comment]
I think for 3 what we need to do is come up with a heuristic for detecting which side the override is coming from. Because of course there are actually two potential filibuster overrides and two veto overrides depending on the "direction" of the bill. Let's just think about the filibuster override.

Consider two cases; one where a vote is non-unanimous but non-ideological. Suppose a vote is near-unanimous and the few nays are distributed at random through the spectrum; then it is unclear if the filibuster override is the 60th right or 60th leftmost legislator. We should not note an overrider.

Suppose instead that the vote is cleanly a left-right vote, then if the right-most member votes Yea then the filibuster override is the 60th member counting right to left, while if the left-most member votes Yea then the filibuster override is the 60th member counting left to right. 

So should the heuristic to be just to sanity check the 1st and nth voters, ensure they are on opposing sides, and count from the side where the Yea voter is? Or use the cutline angle data to compute whether a vote is sufficiently ideological?

**Comment by JeffreyBLewis** [comment]
Maybe for now, we just keep it simple and have filibuster pivots at positions 40 and 60 and veto pivots at 33 and 66.   In the future we can also have an option for a version that accounts for features of the vote (projects ideal points onto a line orthogonal to the cutline and then only plots the relevant med, fil, and veto locations.

**Comment by aaronrudkin** [comment]
1 and 2 are done--we have tooltips for every member with their ideology and probability of voting.

I have a question for 3. The question is--Is the veto override 2/3rds of those voting, or 2/3rds of the entire body of the House? i.e. suppose 100 people abstain, is the veto override ceil((435-100)*(2/3)) = 224 or ceil(435*(2/3)) = 290? I know the Filibuster override is 60 members total regardless of attendance.

**Comment by aaronrudkin** [comment]
The decoration for the median member and filibuster/cloture pivots are in when sorting by ideology. It's a small red asterisk and the user gets a text note in their tooltip about why they're a pivotal voter.

For median, I give one median if there's an odd number of members, and two if there's an even. For filibuster override, I do 60th and n-60th where n is the total number of members, and only calculate it for Senate votes post-1975 (when Cloture changed to 60). I calculate the ranking based only on members who have ideological scores, so in practice they might be slightly off until the remainder of the people in the 115th get scores.

Updating this to Post-Launch pending answers about how to handle the Veto Override.

**Comment by aaronrudkin** [comment]
I added member bio photos to these tooltips and generally improved design.

**Comment by aaronrudkin** [comment]
Veto override is in, so we are done here.
