### ISSUE TITLE
Search for text with accents

### ISSUE THREAD

**Issue by adamboche** [JeffreyBLewis/WebVoteView#96]
We'd like to be able to find people who have accents in their names, or bills that have accents in their names, without having to type the accented characters. For example, searching `cardenas` should find `CÁRDENAS, Tony`. I think the new version of Mongo we're now using makes this possible if it is feasible to include [this feature](https://docs.mongodb.com/manual/reference/operator/query/text/) in the API:

```
{
  $text:
    {
      $search: <string>,
      $language: <string>,
      $caseSensitive: <boolean>,
      $diacriticSensitive: <boolean>
    }
}
```

**Comment by lukesonnet** [comment]
but what if people put in the effort to include an accent? Should we just ignore it and make it insensitive to accents?

**Comment by JeffreyBLewis** [comment]
In the futurem we might want to be the case if include a diacritic in the search a check box appears that allows you choose to match exactly or not.   I agree with Adam that the best default is probably the insensitive one as much of the older material in the db does not include them.

**Comment by aaronrudkin** [comment]
Isn't the default for diacriticSensitivity false? I thought we already did this.

**Comment by aaronrudkin** [comment]
Separately, searches with diacritics currently crash @lukesonnet I thought you fixed something with this at one point. Try searching Cárdenas and watch as we spool endlessly.

**Comment by adamboche** [comment]
Looks like 'Cardenas' finds nobody.
db.voteview_members.findOne({bioname: /cardenas/i}) finds nobody as well.
I'm not sure what query is actually run by the api though?

**Comment by aaronrudkin** [comment]
The API uses a regex by default, like your search, if you only give a single name or if you specify as Last, First--intending to get an exact match. If you search Tony Cardenas you get the result you'd expect because it uses the fulltext index which is already insensitive to diacritics.

Summary of results at present:
1. Cárdenas gives us Tony Cárdenas (uses regex) ✔️
2. Cardenas gives us no results (regex) ❌
3. Tony Cardenas gives us Tony Cárdenas (uses fulltext) ✔️
4. Cardenas, Tony gives us no results (regex) ❌
5. Cárdenas, Tony gives us Tony Cárdenas (regex) ✔️

Looking online it seems like there might be some issues associated with this exact problem with a regex. The diacriticSensitive thing above doesn't seem to apply apply to regex searches (and it defaults to false, so that was our desired behaviour anyway).

Can we punt on this until later?

**Comment by adamboche** [comment]
I don't have a good understanding of all the considerations involved in the search, so this may not be well advised. At this time `bioname` is now text-indexed so `db.voteview_members.find({$text: {$search: 'cardenas'}})` (no accent, no capitalization) does find him. I wonder if it might be reasonable for right now to use the text search instead of regex in this case?

**Comment by aaronrudkin** [comment]
I fixed this.

So the basic issue is that with fulltext, you get diacritic insensitivity, but not partial word matches (i.e. search for _clinto_ and get no results), while with regex you get partial word matches, but it's slow, and you don't get diacritic insensitivity.

I solved it by searching with fulltext first, and if there are no results, trying the same search as a regex. It means failing searches will be modestly slower, but we will have better behaviour. Yay!
